name: tf_env
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.9.9=haa95532_0
  - expat=2.7.1=h8ddb27b_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.2=pyhc872135_1
  - python=3.11.14=h981015d_0
  - setuptools=80.9.0=py311haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - tk=8.6.15=hf199647_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py311haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - absl-py==2.3.1
      - astunparse==1.6.3
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - contourpy==1.3.3
      - cycler==0.12.1
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h5py==3.15.1
      - idna==3.11
      - imutils==0.5.4
      - joblib==1.5.2
      - keras==3.11.3
      - kiwisolver==1.4.9
      - libclang==18.1.1
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - ml-dtypes==0.5.3
      - namex==0.1.0
      - numpy==2.2.6
      - opencv-python==4.12.0.88
      - opt-einsum==3.4.0
      - optree==0.17.0
      - packaging==25.0
      - pillow==12.0.0
      - protobuf==6.33.0
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - requests==2.32.5
      - rich==14.2.0
      - scikit-learn==1.7.2
      - scipy==1.16.2
      - six==1.17.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - typing-extensions==4.15.0
      - urllib3==2.5.0
      - werkzeug==3.1.3
      - wrapt==2.0.0
prefix: C:\Users\sarva\anaconda3\envs\tf_env
